export const COMMAND_SPLITTING_SYMBOL = ' ';
export const PROMPT_FORMAT = 'full';
export const PROMPT_SPLITTING_SYMBOL = ' / ';
export const PROMPT_PREFIX = '';
export const PROMPT_SUFFIX = '>';
export const PROMPT_DEFAULT = `${PROMPT_SUFFIX}${COMMAND_SPLITTING_SYMBOL}`;

export const I18N_FALLBACK_LANGUAGE = 'en';
export const I18N_DEFAULT_NS = 'internal';
export const I18N_EXTERNAL_NS = 'additional';

export const MESSAGE_CODES = {
	SUCCESS_EXECUTE: 200,
	SUCCESS_AUTOCOMPLETE: 300,
	ERROR_GENERIC: 400,
	ERROR_CONTEXT_NOT_FOUND: 401,
	ERROR_NODE_NOTFOUND: 402,
	ERROR_INVALID_COMMAND: 403,
	ERROR_MISSING_PARAMETER: 404,
	ERROR_INVALID_PARAMETER: 405,
	ERROR_INVALID_FORMAT: 406,
	ERROR_GENERIC_ACTION_NOT_FOUND: 407,
	ERROR_IMPLICIT_COMMAND_GENERIC: 500,
};
