import {
	CONTEXT_NAME as FONTS_CONTEXT_NAME,
	COMMAND_NAMES as FONT_COMMAND_NAMES,
} from './fontSettings';
import {
	CONTEXT_NAME as STYLING_CONTEXT_NAME,
	COMMAND_NAMES as STYLING_COMMAND_NAMES,
} from './stylingSettings';
import {
	CONTEXT_NAME as UI_SETTINGS_CONTEXT_NAME,
	COMMAND_NAMES as UI_SETTINGS_COMMAND_NAMES,
} from './uiSettings';

export const COMMAND_NAMES = {
	...FONT_COMMAND_NAMES,
	...STYLING_COMMAND_NAMES,
	...UI_SETTINGS_COMMAND_NAMES,
};

export const CONTEXT_NAMES = {
	SETTINGS_CONTEXT: UI_SETTINGS_CONTEXT_NAME,
	FONTS: FONTS_CONTEXT_NAME,
	STYLING: STYLING_CONTEXT_NAME,
};
