import { CONTEXT_NAME as ROOT_CONTEXT_NAME, COMMAND_NAMES as ROOT_COMMAND_NAMES } from './game';
import {
	CONTEXT_NAME as CHARACTER_CONTEXT_NAME,
	COMMAND_NAMES as CHARACTER_COMMAND_NAMES,
} from './characterConfiguration';
import {
	CONTEXT_NAME as BODY_CONTEXT_NAME,
	COMMAND_NAMES as BODY_COMMAND_NAMES,
} from './bodyConfiguration';
import {
	CONTEXT_NAME as HEAD_CONTEXT_NAME,
	COMMAND_NAMES as HEAD_COMMAND_NAMES,
} from './headConfiguration';
import {
	CONTEXT_NAME as HAIR_CONTEXT_NAME,
	COMMAND_NAMES as HAIR_COMMAND_NAMES,
} from './hairConfiguration';

export const COMMAND_NAMES = {
	...ROOT_COMMAND_NAMES,
	...CHARACTER_COMMAND_NAMES,
	...BODY_COMMAND_NAMES,
	...HEAD_COMMAND_NAMES,
	...HAIR_COMMAND_NAMES,
};

export const CONTEXT_NAMES = {
	ROOT_CONTEXT: ROOT_CONTEXT_NAME,
	CHARACTER_CONTEXT: CHARACTER_CONTEXT_NAME,
	BODY_CONTEXT: BODY_CONTEXT_NAME,
	HEAD_CONTEXT: HEAD_CONTEXT_NAME,
	HAIR_CONTEXT: HAIR_CONTEXT_NAME,
};
