name: Manual Release

on:
   workflow_dispatch:
      inputs:
         version:
            description: 'Version number for this release (e.g. 1.2.3)'
            required: true
            type: string

permissions:
  contents: write

jobs:
   validate-and-build:
      name: Run pre-release checks
      uses: ./.github/workflows/common.yml
      with:
         build-artifact: true
         version: ${{ github.event.inputs.version }}

   release:
      name: Create Manual Release
      needs: validate-and-build # ✅ ensures it runs AFTER artifacts are ready
      runs-on: ubuntu-latest

      steps:
         # 1️⃣ Checkout the repo
         - name: Checkout repository
           uses: actions/checkout@v4
           with:
              ref: ${{ github.ref_name }}

         # 4️⃣ Create a Git tag based on input version
         - name: Create git tag
           id: tag
           run: |
              TAG="${{ github.event.inputs.version }}"
              VERSION="v${{ github.event.inputs.version }}"

              echo "Checking if tag $VERSION exists..."
              git fetch origin --tags --force --prune

              if git rev-parse "$VERSION" >/dev/null 2>&1; then
                echo "✅ Tag $VERSION already exists. Skipping tag creation."
               else
                  echo "🏷️ Releasing version $VERSION"

                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor }}@users.noreply.github.com"

                  # This handles package.json + commit + tag
                  npm version $TAG -m "auto commit: release v%s"

                  # Push commit + tag
                  git push origin ${{ github.ref_name }} --follow-tags
               fi

         - name: Download build artifact
           uses: actions/download-artifact@v4
           with:
              name: build-${{ github.ref_name }}-${{ github.event.inputs.version }}
              path: dist

         #- name: Download build artifact
         #  uses: actions/download-artifact@v4
         #  with:
         #     name: demo-${{ github.ref_name }}-${{ github.event.inputs.version }}
         #     path: dist

         # 5️⃣ Create a GitHub Release
         - name: Create GitHub Release
           uses: softprops/action-gh-release@v2
           with:
              tag_name: v${{ github.event.inputs.version }}
              name: Release v${{ github.event.inputs.version }}
              generate_release_notes: true
              files: dist/**
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
