name: Release

on:
   workflow_dispatch:
      inputs:
         version:
            description: 'Version number for this release (e.g. 1.2.3)'
            required: true
            type: string

permissions:
   contents: write

jobs:
   run-library-ci:
      name: Run pre-release checks
      uses: ./.github/workflows/library.yml
      with:
         build-artifact: true
         version: ${{ github.event.inputs.version }}

   run-demo-ci:
      name: Run pre-release checks
      uses: ./.github/workflows/demo.yml
      with:
         version: ${{ github.event.inputs.version }}

   release:
      name: Create Manual Release
      needs: [run-library-ci, run-demo-ci] # ✅ ensures it runs AFTER artifacts are ready
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4
           with:
              ref: ${{ github.ref_name }}

         - name: Create git tag
           id: tag
           run: |
              TAG="${{ github.event.inputs.version }}"
              VERSION="v${{ github.event.inputs.version }}"

              echo "Checking if tag $VERSION exists..."
              git fetch origin --tags --force --prune

              if git rev-parse "$VERSION" >/dev/null 2>&1; then
                echo "✅ Tag $VERSION already exists. Skipping tag creation."
               else
                  echo "🏷️ Releasing version $VERSION"

                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor }}@users.noreply.github.com"

                  # This handles package.json + commit + tag
                  npm version $TAG -m "auto commit: release v%s"

                  # Push commit + tag
                  git push origin ${{ github.ref_name }} --follow-tags
               fi

         - name: Download build artifact
           uses: actions/download-artifact@v4
           with:
              name: build-${{ github.event.inputs.version }}-${{ github.sha }}
              path: artifacts

         - name: Download demo artifact
           uses: actions/download-artifact@v4
           with:
              name: demo-${{ github.event.inputs.version }}-${{ github.sha }}
              path: artifacts

         - name: Create GitHub Release
           uses: softprops/action-gh-release@v2
           with:
              tag_name: v${{ github.event.inputs.version }}
              name: Release v${{ github.event.inputs.version }}
              generate_release_notes: true
              files: |
                 artifacts/build-${{ github.event.inputs.version }}-${{ github.sha }}.zip
                 artifacts/demo-${{ github.event.inputs.version }}-${{ github.sha }}.zip
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
